// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using Fantasy.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fantasy.Net.Migrations
{
    [DbContext(typeof(PgSession))]
    partial class PgSessionModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("default")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetShare.内容.邮箱.系统邮件回复数据", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EmbbededMulti")
                        .HasColumnType("jsonb")
                        .HasColumnName("_m");

                    b.Property<string>("EmbbededSingle")
                        .HasColumnType("jsonb")
                        .HasColumnName("_s");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentType")
                        .HasColumnType("bigint");

                    b.Property<string>("主题")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("已删除")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("最近消息时间")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("消息内容")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<byte>>("消息发送方")
                        .IsRequired()
                        .HasColumnType("smallint[]");

                    b.PrimitiveCollection<List<DateTime>>("消息时间")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone[]");

                    b.Property<int>("用户已读条数")
                        .HasColumnType("integer");

                    b.Property<int>("系统邮件Id")
                        .HasColumnType("integer");

                    b.Property<string>("账号")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("账号");

                    b.HasIndex("ParentType", "ParentId");

                    b.ToTable("系统邮件回复数据", "NetShare_内容_邮箱");
                });

            modelBuilder.Entity("NetShare.内容.邮箱.通信线程数据", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EmbbededMulti")
                        .HasColumnType("jsonb")
                        .HasColumnName("_m");

                    b.Property<string>("EmbbededSingle")
                        .HasColumnType("jsonb")
                        .HasColumnName("_s");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentType")
                        .HasColumnType("bigint");

                    b.Property<string>("主题")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("发送者已删除")
                        .HasColumnType("boolean");

                    b.Property<int>("发送者已读条数")
                        .HasColumnType("integer");

                    b.Property<string>("发送者账号")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("接收者已删除")
                        .HasColumnType("boolean");

                    b.Property<int>("接收者已读条数")
                        .HasColumnType("integer");

                    b.Property<string>("接收者账号")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("最近消息时间")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("消息内容")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<byte>>("消息发送方")
                        .IsRequired()
                        .HasColumnType("smallint[]");

                    b.PrimitiveCollection<List<DateTime>>("消息时间")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone[]");

                    b.HasKey("Id");

                    b.HasIndex("发送者账号");

                    b.HasIndex("接收者账号");

                    b.HasIndex("ParentType", "ParentId");

                    b.ToTable("通信线程数据", "NetShare_内容_邮箱");
                });

            modelBuilder.Entity("NetShare.内容.邮箱.邮箱数据", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EmbbededMulti")
                        .HasColumnType("jsonb")
                        .HasColumnName("_m");

                    b.Property<string>("EmbbededSingle")
                        .HasColumnType("jsonb")
                        .HasColumnName("_s");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentType")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<List<int>>("已删除系统邮件Ids")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<List<int>>("已读系统邮件Ids")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<List<long>>("系统邮件回复Ids")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.Property<string>("账号")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<long>>("通信线程Ids")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.HasKey("Id");

                    b.HasIndex("账号")
                        .IsUnique();

                    b.HasIndex("ParentType", "ParentId");

                    b.ToTable("邮箱数据", "NetShare_内容_邮箱");
                });

            modelBuilder.Entity("NetShare.用户.用户关联信息", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EmbbededMulti")
                        .HasColumnType("jsonb")
                        .HasColumnName("_m");

                    b.Property<string>("EmbbededSingle")
                        .HasColumnType("jsonb")
                        .HasColumnName("_s");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentType")
                        .HasColumnType("bigint");

                    b.Property<string>("实名")
                        .HasColumnType("text");

                    b.Property<string>("实名ID号")
                        .HasColumnType("text");

                    b.Property<string>("手机号")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("手机号地区码")
                        .HasColumnType("text");

                    b.Property<string>("邮箱")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("实名");

                    b.HasIndex("实名ID号");

                    b.HasIndex("邮箱");

                    b.HasIndex("ParentType", "ParentId");

                    b.HasIndex("手机号地区码", "手机号")
                        .IsUnique();

                    b.ToTable("用户关联信息", "NetShare_用户");
                });

            modelBuilder.Entity("NetShare.用户.用户基本设置", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EmbbededMulti")
                        .HasColumnType("jsonb")
                        .HasColumnName("_m");

                    b.Property<string>("EmbbededSingle")
                        .HasColumnType("jsonb")
                        .HasColumnName("_s");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentType")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentType", "ParentId");

                    b.ToTable("用户基本设置", "NetShare_用户");
                });

            modelBuilder.Entity("NetShare.用户.用户数据", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EmbbededMulti")
                        .HasColumnType("jsonb")
                        .HasColumnName("_m");

                    b.Property<string>("EmbbededSingle")
                        .HasColumnType("jsonb")
                        .HasColumnName("_s");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentType")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("上次登入时间")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("头像")
                        .HasColumnType("bytea");

                    b.Property<string>("密码")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("登记时间")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("账号")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("账号")
                        .IsUnique();

                    b.HasIndex("ParentType", "ParentId");

                    b.ToTable("用户数据", "NetShare_用户");
                });

            modelBuilder.Entity("NetShare.用户.用户设备信息", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EmbbededMulti")
                        .HasColumnType("jsonb")
                        .HasColumnName("_m");

                    b.Property<string>("EmbbededSingle")
                        .HasColumnType("jsonb")
                        .HasColumnName("_s");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentType")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<List<string>>("活跃设备")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("活跃设备唯一ID")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<byte>>("活跃设备类型")
                        .IsRequired()
                        .HasColumnType("smallint[]");

                    b.PrimitiveCollection<List<IPAddress>>("设备三次前活跃IP")
                        .IsRequired()
                        .HasColumnType("inet[]");

                    b.PrimitiveCollection<List<bool>>("设备允许直接登录")
                        .IsRequired()
                        .HasColumnType("boolean[]");

                    b.PrimitiveCollection<byte[]>("设备所属性质")
                        .IsRequired()
                        .HasColumnType("smallint[]");

                    b.PrimitiveCollection<List<IPAddress>>("设备最近活跃IP")
                        .IsRequired()
                        .HasColumnType("inet[]");

                    b.PrimitiveCollection<List<DateTime>>("设备最近登入时间")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone[]");

                    b.PrimitiveCollection<List<IPAddress>>("设备次近活跃IP")
                        .IsRequired()
                        .HasColumnType("inet[]");

                    b.Property<string>("账号")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("账号");

                    b.HasIndex("ParentType", "ParentId");

                    b.ToTable("用户设备信息", "NetShare_用户");
                });

            modelBuilder.Entity("NetShare.角色数据", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EmbbededMulti")
                        .HasColumnType("jsonb")
                        .HasColumnName("_m");

                    b.Property<string>("EmbbededSingle")
                        .HasColumnType("jsonb")
                        .HasColumnName("_s");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentType")
                        .HasColumnType("bigint");

                    b.Property<string>("名字")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentType", "ParentId");

                    b.ToTable("角色数据", "default");
                });

            modelBuilder.Entity("NetShare.音游.AudioMetadata_Shadow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<object>("Json")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("AudioMetadata_Doc", "NetShare_音游");
                });

            modelBuilder.Entity("NetShare.音游.ChartMetadata_Shadow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<object>("Json")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("ChartMetadata_Doc", "NetShare_音游");
                });

            modelBuilder.Entity("NetShare.音游.战贴", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EmbbededMulti")
                        .HasColumnType("jsonb")
                        .HasColumnName("_m");

                    b.Property<string>("EmbbededSingle")
                        .HasColumnType("jsonb")
                        .HasColumnName("_s");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentType")
                        .HasColumnType("bigint");

                    b.Property<int>("人气")
                        .HasColumnType("integer");

                    b.Property<long>("创作者Id")
                        .HasColumnType("bigint");

                    b.Property<string>("创作者名")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("创建时间")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("挑战人数")
                        .HasColumnType("integer");

                    b.Property<string>("标题")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<long>>("混编曲目Ids")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.PrimitiveCollection<List<float>>("混编终点")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.PrimitiveCollection<List<float>>("混编起点")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.Property<int>("点赞数")
                        .HasColumnType("integer");

                    b.Property<float>("难度")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("人气");

                    b.HasIndex("创作者Id");

                    b.HasIndex("ParentType", "ParentId");

                    b.ToTable("战贴", "NetShare_音游");
                });

            modelBuilder.Entity("NetShare.音游.用户养成数据", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EmbbededMulti")
                        .HasColumnType("jsonb")
                        .HasColumnName("_m");

                    b.Property<string>("EmbbededSingle")
                        .HasColumnType("jsonb")
                        .HasColumnName("_s");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentType")
                        .HasColumnType("bigint");

                    b.Property<int>("体力")
                        .HasColumnType("integer");

                    b.Property<long>("用户Id")
                        .HasColumnType("bigint");

                    b.Property<int>("等级")
                        .HasColumnType("integer");

                    b.Property<long>("经验值")
                        .HasColumnType("bigint");

                    b.Property<long>("金钱")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentType", "ParentId");

                    b.ToTable("用户养成数据", "NetShare_音游");
                });

            modelBuilder.Entity("NetShare.音游.用户战贴档案", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EmbbededMulti")
                        .HasColumnType("jsonb")
                        .HasColumnName("_m");

                    b.Property<string>("EmbbededSingle")
                        .HasColumnType("jsonb")
                        .HasColumnName("_s");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentType")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<List<long>>("历史战贴Ids")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.PrimitiveCollection<List<DateTime>>("历史挑战时间")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone[]");

                    b.PrimitiveCollection<List<long>>("我的战贴Ids")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.PrimitiveCollection<List<long>>("收藏战贴Ids")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.Property<long>("用户Id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentType", "ParentId");

                    b.ToTable("用户战贴档案", "NetShare_音游");
                });

            modelBuilder.Entity("NetShare.音游.用户游戏设置", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EmbbededMulti")
                        .HasColumnType("jsonb")
                        .HasColumnName("_m");

                    b.Property<string>("EmbbededSingle")
                        .HasColumnType("jsonb")
                        .HasColumnName("_s");

                    b.Property<int>("Miss反馈模式")
                        .HasColumnType("integer");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentType")
                        .HasColumnType("bigint");

                    b.Property<float>("UI音量")
                        .HasColumnType("real");

                    b.Property<bool>("已保存过")
                        .HasColumnType("boolean");

                    b.Property<long>("用户Id")
                        .HasColumnType("bigint");

                    b.Property<int>("画质档")
                        .HasColumnType("integer");

                    b.Property<int>("目标帧率")
                        .HasColumnType("integer");

                    b.Property<float>("背景音量")
                        .HasColumnType("real");

                    b.Property<float>("音符飞行速度")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ParentType", "ParentId");

                    b.ToTable("用户游戏设置", "NetShare_音游");
                });
#pragma warning restore 612, 618
        }
    }
}
